### ISSUE TITLE
Hot reload JavaScript files

### ISSUE THREAD

**Issue by mszekiel** [wpine215/msfs-a320neo#102]
Find a way, ask Asobo/MS how to fast reload aircraft JS files to speed up development. Get more docs about this SDK.

Right not it's impossible to reload JS files during runtime and it's required to restart the FS.
It's only possible to reload HTML/CSS file. 

It would benefit in development process and speed.

**Comment by arvinjarvin** [comment]
Hello.

Microsoft Flight Simulator stores the aircraft logic files in an isolated, and static environment (meaning it is cached throughout) to that of the main gauges (css, xml, html) and as such there isn't much anyone could do.

In theory you could experiment with websockets to achieve what you're doing but it would likely take longer doing that than it would to just restart MFS. 

Arvin
