### ISSUE TITLE
Dev Branch - Starting on Runway bugs out Avionics - No Screens

### ISSUE THREAD

**Issue by 2hwk** [wpine215/msfs-a320neo#104]
Starting on runway instead of cold and dark spawns you with no displays.

Turning eng master 1 on and off is a temporary solution. 

![image](https://user-images.githubusercontent.com/15316958/91290419-28aa1f00-e7c6-11ea-873e-f4d6305e3012.png)

**Comment by ninjomcs** [comment]
Duplicate issue.
