### ISSUE TITLE
[SUGGESTION] Make the MCDU display DEV or STABLE version.

### ISSUE THREAD

**Issue by LorDawid** [wpine215/msfs-a320neo#105]
When you have the dev branch installed, the MCDU shows "Mod Version: 0.1.1" 
Thats one of the easiest ways to check if you have the mod installed. But the problem is that when the new stable release will come online, the stable version will also show 0.1.1 so it would be harded to know what version are you in. In my opinion, the MCDU should show "DEV 0.1.1" or "STABLE 0.1.1"
![Microsoft Flight Simulator Screenshot 2020 08 26 - 13 01 55 63](https://user-images.githubusercontent.com/44745662/91296149-70b44c00-e79c-11ea-9f22-07568b05ad8c.png)

**Comment by arvinjarvin** [comment]
The aircraft status data page has been updated to real standards and I will roll this out when I finish with the required segments
