### ISSUE TITLE
Rejected Takeoff Autobrake Issue

### ISSUE THREAD

**Issue by Leon04nb** [wpine215/msfs-a320neo#117]
Whilst performing a rejected takeoff, the autobrakes don't seem to activate so manual braking is required to stop the aircraft. The spoilers do deploy though.

**Comment by arvinjarvin** [comment]
Hello, this will be looked into and resolved accordingly.

Thanks for raising the issue.
Arvin

**Comment by Venorcis** [comment]
Why was this closed? It's still mentioned as being a problem in #767

**Comment by wpine215** [comment]
Not sure, it seems the original creator closed it, but we have another open issue for it anyway so it doesn't matter.
