### ISSUE TITLE
Please include Fix for Fuel Usage / Thrust Fix

### ISSUE THREAD

**Issue by 0Thomas082** [wpine215/msfs-a320neo#128]
as Reference see Informations here :

Mod engines.cfg

https://www.nexusmods.com/microsoftflightsimulator/mods/6                   (FUEL FIX)
https://www.nexusmods.com/microsoftflightsimulator/mods/20                ( Thrust FIX)

**Comment by wpine215** [comment]
Those fixes are included in this mod.
