### ISSUE TITLE
ECAM display for APU not working in latest dev branch

### ISSUE THREAD

**Issue by nakaori** [wpine215/msfs-a320neo#131]
It appears that the APU ECAM page is not updating during APU spoolup. At some point the APU shows up in the overhead panel and one is able to start engines but the stats are not showing.

**Comment by GlitchedYT** [comment]
Recreated this.
Steps: 
1) Start the APU, wait for it to become available.
2) Turn off APU Master Switch, let the APU turn completely off
3) Restart the APU, no values on the APU ECAM page will appear other than the APU GEN once it is available.

https://imgur.com/z1pd4eW
https://imgur.com/z1pd4eW

**Comment by AdenFlorian** [comment]
Working on a fix

**Comment by AdenFlorian** [comment]
fix is in dev branch

**Comment by AdenFlorian** [comment]
@nakaori could you retest this on latest dev branch and the close this if it looks good?

**Comment by nakaori** [comment]
Looks good now. Display is working fine for me.
