### ISSUE TITLE
BRK Fan Missing

### ISSUE THREAD

**Issue by GlitchedYT** [wpine215/msfs-a320neo#136]
I don't know how this hasn't been reporting yet but there's no BRK Fan above the Anti Skid/NW Steering
<img width="1920" alt="Desktop Screenshot 2020 08 27 - 09 18 45 20" src="https://user-images.githubusercontent.com/56449691/91452650-d06a3000-e84c-11ea-826e-8c7a7eb2f938.png">

**Comment by becas22** [comment]
Brake Fan is an option. But yes, i never saw an A320 without one.

**Comment by wpine215** [comment]
Can't be addressed until we get the model files from Asobo unfortunately. Closing for now.
