### ISSUE TITLE
APU gauges are still in amber after landing

### ISSUE THREAD

**Issue by starvingjavi** [wpine215/msfs-a320neo#137]
After landing and trying to turn on the APU I would get the flap open message only, The gauges would still be in amber and  with xx regardless of the APU start button being in ON or Available. By the sound I could tell the APU was starting, but with no indication of it in the gauges.

**Comment by AdenFlorian** [comment]
I think this might be fixed by #298

**Comment by starvingjavi** [comment]
It did
