### ISSUE TITLE
Screens stuck on self test in progress

### ISSUE THREAD

**Issue by CoffeePanda0** [wpine215/msfs-a320neo#143]
![image](https://user-images.githubusercontent.com/34898787/91469719-a84df180-e88b-11ea-94d2-2f671f7d1756.png)
After batteries and a source of power (both APU and GPU have this issue) the Engine display and ECAM both are stuck on the self tests after many minutes.

**Comment by CoffeePanda0** [comment]
Also they seem to always be showing that as soon as the battery is on, unlike waiting for power like the other displays

**Comment by michaeldiguiseppi** [comment]
This should be resolved in the latest dev build from about 10 minutes ago. Please re-download and test again.

**Comment by arvinjarvin** [comment]
Hello

This issue has been resolved in the dev branch.

Please follow the following steps to solve the issue locally

- Completely Delete your A32NX folder from community
- Ensure your simulator is closed
- Reinstall from the DEV branch
- Restart your simulator

If you are experiencing further issues please reopen this issue

Arvin
