### ISSUE TITLE
Add ADIRS "ON BAT" and "ALIGN" lights and adjust align time based on latitude, displaying remaining time in upper ECAM

### ISSUE THREAD

**Issue by wpine215** [wpine215/msfs-a320neo#150]

**Comment by arvinjarvin** [comment]
Hi.

Thanks for raising this issue.
It will be solved, and you will be kept updated accordingly.

All the best
Arvin

**Comment by arvinjarvin** [comment]
**Note for other developers working on this:**

Where you are further away from the equator the align time of the IRS takes longer. Hence the reference to latitude.

**Comment by ColdChicken1** [comment]
Would be great to have the horn ringing if we forget the ADIRS on bat for too long too.
