### ISSUE TITLE
APU is on but the bottom dials aren't working

### ISSUE THREAD

**Issue by miniarmagb** [wpine215/msfs-a320neo#156]
![Screenshot (4)](https://user-images.githubusercontent.com/70097051/91497777-7f8f2180-e8b6-11ea-964a-767f0c5d49f9.png)

**Comment by JackZ974** [comment]
have you pressed the START button after the MASTER one?

**Comment by miniarmagb** [comment]
> 
> 
> have you pressed the START button after the MASTER one?

Yes I did, seems the issue has been fixed now so this can be closed.
