### ISSUE TITLE
Can't turn off display 

### ISSUE THREAD

**Issue by SmithFR** [wpine215/msfs-a320neo#165]
![Capture d’écran (177)](https://user-images.githubusercontent.com/70339648/91515136-6edeab80-e8b6-11ea-8bf0-6945e1a7151f.png)

**Comment by wpine215** [comment]
Can you elaborate further?

**Comment by toffee2000** [comment]
I think he meant that the ISFD can’t be turned off, even without electrical power.

**Comment by lousybyte** [comment]
Works fine on the dev branch for me, make sure to turn off the batteries as well for the ISIS.

**Comment by SmithFR** [comment]
Oh sorry I thought that with batteries on and the brightness knob on OFF displays should be off

**Comment by JackZ974** [comment]
True. The 4 displays screens can always be turned off individually by setting their brightness button to the leftmost OFF position

**Comment by topiek-fs** [comment]
Fixed in #335
