### ISSUE TITLE
IRS button and start screen doesn't work for me

### ISSUE THREAD

**Issue by oliveiralberto** [wpine215/msfs-a320neo#167]
I don't know why. But for me IRS buttons doesn't work, Steel inoop. And also the start screen when power on the aircraft steel as the default plane. Ecam update works perfect.

**Comment by SmithFR** [comment]
Are you using the dev version ?

**Comment by oliveiralberto** [comment]
> Are you using the dev version ?

Sorry I'm no expert on this. What do you mean with dev version? I donwload msfs-a320neo-0.1.1.zip and I put the A32NX folder into the comunnity folder. Ecam work "good" but IRS button and start screen doesn't.

**Comment by SmithFR** [comment]
There is a master branch with a stable version but less functionality and a developer branch with an unstable version with the latest releases where bugs are expected

Here is how to install the dev version:
![DEV](https://user-images.githubusercontent.com/70339648/91516842-7dc75d00-e8ba-11ea-914a-977539d3a8e6.png)

**Comment by oliveiralberto** [comment]
Ohh. thank you. I will try this dev version.
