### ISSUE TITLE
Can this plane be optimized?

### ISSUE THREAD

**Issue by CaptainKeeble** [wpine215/msfs-a320neo#168]
I was wondering if there would be any way of optimizing this plane as its impossible to run on some systems and on the ground at big airports like KLAX your FPS will tank. The performance of this plane is one of its biggest problems and I hope to see it be fixed.

Thanks.

**Comment by NathanInnes** [comment]
Try have a go at this, haven't tried it myself but people are saying they have an improvement. 

https://forums.flightsimulator.com/t/small-js-config-file-mod-to-gain-10-15-fps-in-airliners-and-glass-cockpit-planes/221308

**Comment by CaptainKeeble** [comment]
> Try have a go at this, haven't tried it myself but people are saying they have an improvement.
> 
> https://forums.flightsimulator.com/t/small-js-config-file-mod-to-gain-10-15-fps-in-airliners-and-glass-cockpit-planes/221308

I have already tried that, but it made the avionics look laggy. And when I changed it to the setting I liked (in the JS file) my FPS boost was gone. I’m hoping there will be a different way to improve FPS.

**Comment by wpine215** [comment]
Closing issue as it doesn't pertain to a bug specific to the A320neo but the simulator as a whole.
