### ISSUE TITLE
IRS Won't Align

### ISSUE THREAD

**Issue by rdjm23** [wpine215/msfs-a320neo#187]
PFD Comes Alive but ND won't align nor will heading calibrate

**Comment by DoToAdventures** [comment]
How long have you waited? It takes a few minutes. Someone on the Discord earlier reported it took them 10 minutes to align from EHAM

**Comment by rdjm23** [comment]
Sped up in game time and waited over 30 minutes. Restarted game also

**Comment by rdjm23** [comment]
All sorted now thats me just being impatient - keep up the great work!
