### ISSUE TITLE
Seat Belts ECAM Memo Turns Orange during T/O and stays orange

### ISSUE THREAD

**Issue by GlitchedYT** [wpine215/msfs-a320neo#193]
The seat belts ecam memo should not change color at any phase of the flight, it should remain green throughout the whole flight.

https://imgur.com/7ORDiVF

**Comment by ArthurHetem** [comment]
Here isn't only the seat belt

![ECAM_Yellow](https://user-images.githubusercontent.com/7545272/91584206-b0a83a00-e928-11ea-87e9-c5476c000dd3.png)

**Comment by NathanInnes** [comment]
Trying to see if I can fix it

**Comment by wpine215** [comment]
Fixed by #222
