### ISSUE TITLE
APU GEN info

### ISSUE THREAD

**Issue by LorDawid** [wpine215/msfs-a320neo#20]
My APU GEN info doesn't show up when there's no FLAP OPEN message. 
![Microsoft Flight Simulator Screenshot 2020 08 23 - 23 43 26 88](https://user-images.githubusercontent.com/44745662/90989533-be616680-e59a-11ea-861f-a4e986107f72.png)

**Comment by tyler58546** [comment]
The APU GEN info is not supposed to show until the flap is open. See https://www.youtube.com/watch?v=Im0OFRxImYw

**Comment by LorDawid** [comment]
But still the info should come up as you turn on APU master, not when the flap open comes alive (you can see this in this video)

**Comment by noga-aviator** [comment]
i claim the issue

**Comment by noga-aviator** [comment]
now resolved in my pull request, waiting to merge into dev branch

**Comment by noga-aviator** [comment]
fixed, closing
