### ISSUE TITLE
Mod not activated despite correct installation path

### ISSUE THREAD

**Issue by luiskjr** [wpine215/msfs-a320neo#211]
Guess what
I have put the correct A32NX folder in my Community directory (where Liveires folder is and i can see my liveries) also check the folder shows in DV mode Watch Bases.

However...no luck,  three buttons in overhead are INOP and they turn on as soon as Battery is on Mod not activatre

any clues for a reason?

**Comment by ocram9** [comment]
Did you put the mod in the Packages folder or the community folder? The A32NX folder needs to be inside the community folder. If you did install it correctly, are you using the dev version?

**Comment by luiskjr** [comment]
Installed corrected. Now its working

i deleted the AX32N included msfs-a320neo-master and installed AX32N in the dev msfs-a320neo-dev-0.1.1
and now it works.
