### ISSUE TITLE
Engine Sounds too loud / Sound adjustments

### ISSUE THREAD

**Issue by KemalOues** [wpine215/msfs-a320neo#217]
The sounds of the engines are too loud in the virtual cockpit. Also the transition of the flaps are not hearable in the cockpit in real.
There need to be many sound adjustments too.

An example from a real flight:
https://www.youtube.com/watch?v=cv41hm4JEB8

**Comment by apolinski** [comment]
Engine sound is a personal preference. I disagree that it is too loud.

**Comment by nobodyn0se** [comment]
For now, you can lower the aircraft engines slider in the sound settings to about 30-35%. That would give you better results.

**Comment by Curtis-VL** [comment]
Closing the issue as this can be resolved via in-game settings. :)
