### ISSUE TITLE
Rollout mode on PFD stays on after landing

### ISSUE THREAD

**Issue by ukflyer** [wpine215/msfs-a320neo#226]
Rollout mode on PFD stays on after landing, i think it usually disengages when 25 degrees off the inbound runway course

**Comment by Curtis-VL** [comment]
Will look into this, thanks!

**Comment by Curtis-VL** [comment]
Will be fixed in the a pull request soon, will link it here when it's up!

**Comment by ukflyer** [comment]
Perfect thank you!

**Comment by Curtis-VL** [comment]
#236 Fixed in this pull request!

**Comment by ukflyer** [comment]
this works very well thank you

**Comment by wpine215** [comment]
Resolved
