### ISSUE TITLE
A320NX fix uses frames as a clock

### ISSUE THREAD

**Issue by apolinski** [wpine215/msfs-a320neo#233]
The recent FPS fix on forums.flightsimulator.com reduces the frame rate of the glass displays in order to improve overall FPS. When used along with the A320NX mod, several systems like APU startup and initial system check take much longer than usual to complete. This suggests that mod is using a frame counter as a clock instead of an actual clock function. If so, this is bad practice and violates industry standards. It should be investigated and replaced with an actual clock or timer function.

**Comment by ninjomcs** [comment]
All the timers use deltaTime afaik.

**Comment by Benjozork** [comment]
for reference: was discussed on A32NX discord #general-systems channel

https://discordapp.com/channels/738864299392630914/739527931910553651/749187173823021066

**Comment by wpine215** [comment]
If you took the time to glance at the code or even run a stopwatch against certain times processes with and without the FPS fix, you would see that none of the systems are dependent on framerate.
