### ISSUE TITLE
[dev] LS button indicator has inconsistent brightness vs rest of cockpit

### ISSUE THREAD

**Issue by 2hwk** [wpine215/msfs-a320neo#241]
Tested on dev build. Landing system (LS) indicator has slightly different brightness and/or colour to the rest of the pushbuttons.

(Or the rest are too bright??)

(Not related to lighting conditions, see screenshots below)

![image](https://user-images.githubusercontent.com/15316958/91652783-fa318a00-eacc-11ea-9baa-a04d1bd32d6b.png)

![image](https://user-images.githubusercontent.com/15316958/91652813-2f3ddc80-eacd-11ea-81a4-38cdd63acbef.png)

![image](https://user-images.githubusercontent.com/15316958/91652872-9f4c6280-eacd-11ea-9ed6-6c01c96f8dc6.png)

![image](https://user-images.githubusercontent.com/15316958/91652939-5cd75580-eace-11ea-929a-adf6c0638841.png)

Commit ID: 37d48fea170c1fddcee0c28f31f69ae21d0e214e

**Comment by ukflyer** [comment]
Hi also raised here? Cheers. https://github.com/wpine215/msfs-a320neo/issues/67

**Comment by 2hwk** [comment]
![image](https://user-images.githubusercontent.com/15316958/91783565-341ca080-ec33-11ea-8d4b-03f2e5deb657.png)

LS brightness is linked with panel lighting brightness. Updating title.

Also in #271 and #67

**Comment by 2hwk** [comment]
As this has been determined to be a dupe of #67 issue is now closed.
