### ISSUE TITLE
Autopilot not showing changes in the autopilot panel

### ISSUE THREAD

**Issue by larrydingus** [wpine215/msfs-a320neo#242]
I rotate the knobs on the autopilot panel but nothing changes on the glareshield. I can see the changes on the PFD so the knobs and autopilot appear to be working but on the glareshield the altitude is stuck on 5000 and none of the dashes change to numbers when I change modes.

**Comment by ukflyer** [comment]
i only just went to test out the latest dev version and noticed this :(

**Comment by larrydingus** [comment]
Just tried flying and the autopilot seems to be working except for maybe the "level off aircraft" knob. Not too familiar with the a320 but I set the plane up in a 1000fpm climb (referencing the PFD) and was climbing to 8000 out of 4000 and I kept pushing the V/S knob up to level the plane but it wasn't doing anything. I may just be dumb and not doing it right but if someone else could try seeing if it works that would be great.

**Comment by wpine215** [comment]
Issue fixed.
