### ISSUE TITLE
Weird bug, Mod isn't work in 100%

### ISSUE THREAD

**Issue by Arthvr96** [wpine215/msfs-a320neo#246]
How title tells, in my case mod isn't working in 100%.
On the beginning I will mark, that I made sure of the correct installation this extension. 
I pasted "A32NX" folder to the indicated location. (Packages\Community).

After restart mfs2020 I noticed the changes. When I was switching display mode (ls/rose nav/nav/arc/plan) on the screen i could see inscription "mode change" also buttons with informations about "APU" and "DOOR" started works correctly (before install mode, this buttons was inactive of course). 

What doesn't works correctly ? 
Whole ADIRS panel is still inactive, also "no smoking" and "seat belts" switches. 
On the panel AIR COND, switches "COCPIT", "FWD CABIN" and "AFT CABIN" are also inactive.

I have no idea what can cause this problem. I tested this mod on the default liveries.

**Comment by ocram9** [comment]
Did you install the dev version? Those changes aren't in the stable release yet. If you don't have the dev version installed, you can get it here: https://github.com/wpine215/msfs-a320neo/tree/dev-0.1.1

**Comment by Arthvr96** [comment]
I'll try, thx

**Comment by wpine215** [comment]
Closing issue, installation help doesn't belong on Github.
