### ISSUE TITLE
Cruise angle

### ISSUE THREAD

**Issue by ukflyer** [wpine215/msfs-a320neo#253]
Probably not something that can be fixed by the gurus here, but does anyone think the cruise angle is too high? Normally i would expect 2.5 degrees but i'm getting close to 5 at 60T weight. thanks!

![aoa_cruise](https://user-images.githubusercontent.com/70434502/91664602-476f2500-eae8-11ea-92eb-a6ec45f94afd.png)

**Comment by Meqolo** [comment]
Could be fixed by increasing the Cl of the horizontal stab and decreasing wing Cl, will result in the h stab compensating for wing lift, and therefore pushing the nose down.

Could also increase the wing incidence of the h stab for same effect, but it may cause other issues with flight controls.
