### ISSUE TITLE
mod wont work at all

### ISSUE THREAD

**Issue by Pilotcraft1234** [wpine215/msfs-a320neo#256]
Hi there sorry for this i have put the mod back A32NX in C:\Users\[YOUR USERNAME]\AppData\Local\Packages\Microsoft.FlightSimulator_RANDOMLETTERS\LocalCache\Packages\Community`.
and re loaded the sim but it still doesnt seem to have worked i have also installed java in case that was the issue hope you can help :) and thank you in advanced :)

**Comment by NathanInnes** [comment]
![image](https://user-images.githubusercontent.com/18389085/91669110-5a92ec80-eb0a-11ea-89c7-48e44c72c9c7.png)
Try reserve this github for bugs. If you have any other issues please join the discord :) https://discord.gg/aFsuAd

**Comment by lrargerich** [comment]
How do you know it didn't work? Can you spawn an A320 somewhere or not?
