### ISSUE TITLE
All Main Displays will not turn on whether on APU power or Ground Power

### ISSUE THREAD

**Issue by gamecocks08** [wpine215/msfs-a320neo#257]
On the latest dev branch, the Main displays will not turn on at all.

**Comment by NathanInnes** [comment]
Ensure your display brightness is set 
![image](https://user-images.githubusercontent.com/18389085/91669291-ae520580-eb0b-11ea-88cc-c707af8fda7b.png)

**Comment by kiwi2021** [comment]
When did you download the dev branch?

**Comment by omarocasio** [comment]
Looking through it now

**Comment by Benjozork** [comment]
@michaeldiguiseppi, can you specify why the "working as intended" tag ? Would be useful for future reference.

**Comment by wpine215** [comment]
@Benjozork OP's displays are off because they didn't turn up the brightness knobs, since they are positioned full left on cold-and-dark startup.

**Comment by michaeldiguiseppi** [comment]
Yeah working as intended tags are for things that aren’t bugs. They’re working as they are intended, like this due to the knobs being down by default. Indicates that we don’t need to investigate more.
