### ISSUE TITLE
LOC mode on PFD disappears when localiser captured (stays on HDG mode)

### ISSUE THREAD

**Issue by ukflyer** [wpine215/msfs-a320neo#258]
LOC mode on PFD disappears when localiser is captured (stays on HDG mode)
G/S mode seems fine (stays on G/S when glideslope captured)

**Comment by Curtis-VL** [comment]
Hey,
Is this happening as of the latest update too?

In my testing, I've had LOC remain active throughout the whole of an ILS approach.
Is it possible you have the FD disabled?

**Comment by flightsimsimon** [comment]
Running a test flight to see if I can replicate on newest release

**Comment by ukflyer** [comment]
Hi guys, 
Am i going mad?? I thought i was used to driving the bus but not so sure now. Maybe i've missed something.
Just tried a YMML/YMML circuit activated APPR mode but get the same, G/S capture mode but no LOC mode on FMA, stays on HDG. I'm using the latest dev files.

![ils1](https://user-images.githubusercontent.com/70434502/91703035-84332e80-eb71-11ea-9743-7c5cb1c3c20a.png)

![ils2](https://user-images.githubusercontent.com/70434502/91703050-872e1f00-eb71-11ea-9dd5-536e876546f1.png)

**Comment by flightsimsimon** [comment]
Tested 31/8 13:23 FMA now working as it should be, LOC and G/S in blue, then green once established, land and flare also shown

**Comment by ukflyer** [comment]
thanks not sure whats going on with mine :(

**Comment by flightsimsimon** [comment]
Have you got that latest release?

**Comment by ukflyer** [comment]
yeh the dev files - before the very latest from a few hours ago.

**Comment by ukflyer** [comment]
i'm just going to test it without the mod see if it also happens in the default

**Comment by flightsimsimon** [comment]
Wet strange 

I just tested it with a group of people on a stream and it worked fine

Are you able to record your approach?

**Comment by ukflyer** [comment]
ye can do, not sure what i'm missing .. approach mode is activated in the FMC and on the control panel

**Comment by flightsimsimon** [comment]
Record it let’s see if we can’t find why it’s not doing it

**Comment by TheoBearman** [comment]
Also having this issue on the master branch.

**Comment by flightsimsimon** [comment]
Master branch I don’t think has been updated yet Theo

**Comment by Curtis-VL** [comment]
Hi @ukflyer,

Ironically, I took a screenshot last night to show off the changed and noticed this exact same thing happen! HDG appeared instead of LOC.

I'll be looking into why that happened today. Typically, I fly on NAV until I intercept, this is likely why I've never seen it before. 👍

**Comment by ukflyer** [comment]
Hey @Curtis-VL 
AH amazing someone else sees it!! :)
Maybe i will try NAV mode to the ILS and see if it happens
Thanks!

**Comment by flightsimsimon** [comment]
Ok you do that and up fly on heading mode to see if I can replicate

**Comment by ukflyer** [comment]
Also noticed in this vid that G/S went into OP DES mode when the A/P came off, don't think he's using the mod tho

at 22:18 mark
https://www.youtube.com/watch?v=cRP4MLEeQAo

**Comment by ukflyer** [comment]
NAV mode was even more interesting!
On approach to AMS i dont have any ILS pointers, have LOC mode but no G/S!! It just gets stranger!!

![ils3](https://user-images.githubusercontent.com/70434502/91741594-da719300-ebac-11ea-8a6e-f212af1d4665.png)

**Comment by ukflyer** [comment]
ah STN approach seems fine in NAV mode, so yeh just seems HDG mode is off :)

![ilsSTNplannedroute](https://user-images.githubusercontent.com/70434502/91746655-d34e8300-ebb4-11ea-9d20-b8e01db3b584.png)

**Comment by Curtis-VL** [comment]
> Also noticed in this vid that G/S went into OP DES mode when the A/P came off, don't think he's using the mod tho
> 
> just after 22:18 mark
> https://www.youtube.com/watch?v=cRP4MLEeQAo

Oh yeah, the default aircraft does some really janky stuff with OP CLB and OP DES!

**Comment by Curtis-VL** [comment]
I'll go do a quick flight and see if I can resolve that issue quickly, as you said, it's likely when flying via heading to a localizer, flying via nav works fine. 👍

**Comment by ukflyer** [comment]
Perfect thanks!

**Comment by Curtis-VL** [comment]
Fixed in the following pull request. #289

**Comment by ukflyer** [comment]
Superb thanks @Curtis-VL

**Comment by Curtis-VL** [comment]
Clossing this as the issue has been fixed in the pull request mentioned above, just waiting for it to be merged!
