### ISSUE TITLE
Autopilot doesnt look as planned

### ISSUE THREAD

**Issue by LorDawid** [wpine215/msfs-a320neo#26]
Look at the right side of the display
![Microsoft Flight Simulator Screenshot 2020 08 24 - 11 11 21 44](https://user-images.githubusercontent.com/44745662/91026617-47a88580-e5fb-11ea-85b4-70fa2e20f123.png)

**Comment by jeffhollan** [comment]
repros for me as well

**Comment by noga-aviator** [comment]
yup, iceman screwed the css

**Comment by wpine215** [comment]
Bug has been fixed in [this commit](https://github.com/wpine215/msfs-a320neo/commit/5b918de24506a6fba8728946a3a75c2c6ab135f1)
