### ISSUE TITLE
Sections of route dissapear when, or just prior to, approaching them

### ISSUE THREAD

**Issue by CaptCQ** [wpine215/msfs-a320neo#264]
Sections of the route displayed on the nav display seem to disappear prior to approaching the way point. It causes the aircraft to then suddenly change course to intercept the next waypoint.

**Comment by omarocasio** [comment]
Does this happen with using the built in Flight Planner? or Does it happen when you manually input the flight plan into the MCDU? or both?

**Comment by omarocasio** [comment]
"Sections of the route displayed on the nav display seem to disappear prior to approaching the way point. It causes the aircraft to then suddenly change course to intercept the next waypoint."

Yea this is how the system works in MSFS

**Comment by Benjozork** [comment]
This seems like expected behaviour.

Do you have any screenshots of what your are describing ?

**Comment by CaptCQ** [comment]
If you look here in this case the nav line disappeared between two waypoints before even reaching the 1st.

![Nav disappearance](https://user-images.githubusercontent.com/70382093/91716074-d3d02500-eb86-11ea-92c7-4c4184d3a010.jpg)

**Comment by omarocasio** [comment]
Yes, this happens with all aircrafts, cause if you see the distance for "D3" in which now is being active the previous way point line will be deleted as the plane makes adjustment to follow the new route

**Comment by CaptCQ** [comment]
After discussing with an airbus pilot, he pointed out this is not correct. As you can see there are two waypoints in white. The only one in white should be the next TO waypoint.
