### ISSUE TITLE
Cockpit completly bugged on last dev branch update

### ISSUE THREAD

**Issue by vref-simulations** [wpine215/msfs-a320neo#276]
![asdasda](https://user-images.githubusercontent.com/67702788/91715355-d66d5300-eb63-11ea-9f5c-88ac1e523069.png)

**Comment by michaeldiguiseppi** [comment]
This should be resolved in the latest dev branch.

**Comment by Curtis-VL** [comment]
@vref-simulations Please close this issue is the issue is resolved! 👍
