### ISSUE TITLE
Textures Missing in newest dev build for every switch

### ISSUE THREAD

**Issue by Ramourti** [wpine215/msfs-a320neo#277]
![Screenshot_13](https://user-images.githubusercontent.com/70518527/91715374-215e8900-ebab-11ea-941e-9a940fc5d7a3.png)
![Screenshot_14](https://user-images.githubusercontent.com/70518527/91715376-23284c80-ebab-11ea-9028-abd5d6da8c11.png)

**Comment by lousybyte** [comment]
Same issue as https://github.com/wpine215/msfs-a320neo/issues/276, wrong `build.py` file pushed, you can can replace the contents of `layout.json` with [THIS](https://gist.githubusercontent.com/lousybyte/b75b247ab2c8a5e024312d4f5f2e5ecc/raw/ffb8ba2e5f5df8cd42c73082caced9e72d459019/layout.json) until it gets fixed if you're not tech savvy.

**Comment by Maraud3** [comment]
> Same issue as #276, wrong `build.py` file pushed, you can replace the contents of `layout.json` with [THIS](https://gist.githubusercontent.com/lousybyte/b75b247ab2c8a5e024312d4f5f2e5ecc/raw/ffb8ba2e5f5df8cd42c73082caced9e72d459019/layout.json) until it gets fixed if you're not tech-savvy.

Fixed for me, thanks!!

**Comment by michaeldiguiseppi** [comment]
This should be resolved in the latest dev branch.

**Comment by Curtis-VL** [comment]
If this issue is resolved @Ramourti then please close the issue! 👍
