### ISSUE TITLE
i need help plz

### ISSUE THREAD

**Issue by medhatmo** [wpine215/msfs-a320neo#280]
i can not find the Microsoft.FlightSimulator_<RANDOMLETTERS>\LocalCache\Packages\Community 
i did buy it i have   packages and commnity in here in the folder installation 
![Screenshot (32)](https://user-images.githubusercontent.com/68933610/91732709-e3606580-eba8-11ea-9cb3-680d25911967.png)
i did copy A32NX in commnity folder like u see in photo and i open fxs and still not work smoke and not work enything
![Screenshot (33)](https://user-images.githubusercontent.com/68933610/91733005-4eaa3780-eba9-11ea-9931-ad4681619e35.png)

can u plz help me 
and here the folder u say i can not see the Microsoft.FlightSimulator C:\Users\[YOUR USERNAME]\AppData\Local\Packages\Microsoft.FlightSimulator_<RANDOMLETTERS>\LocalCache\Packages\Community.
![Screenshot (34)](https://user-images.githubusercontent.com/68933610/91733265-9c26a480-eba9-11ea-88a6-25912e051ae3.png)

i hope u can help me thank u

**Comment by JoeW9** [comment]
In the second picture your in your community folder?

If it's not yours when you download MSFS you get to pick the location of it. If you don't know where it is located then just search in the bar at the top right just type in "community" and it will come up.

**Comment by ocram9** [comment]
The github is meant for bug reports, if you need help installing you can join the discord: https://discord.com/invite/UjzuHMU and go to #installation-help

**Comment by medhatmo** [comment]
> 
> 
> In the second picture your in your community folder?
> 
> If it's not yours when you download MSFS you get to pick the location of it. If you don't know where it is located then just search in the bar at the top right just type in "community" and it will come up.

no its my bro can u help me plz in discord i can not install it  medhat2020#6917  plz add me and help me

**Comment by Meqolo** [comment]
this is not what the github is for, go to the channel #installation-help in the discord
