### ISSUE TITLE
The Altitude

### ISSUE THREAD

**Issue by Kubakuurne** [wpine215/msfs-a320neo#282]
with the master or dev version I don't see the value of the altitude change it stays at  5000ft although if you manipulate is you see the value on the screen.

https://i.imgur.com/kpPFaGk.jpg

also with the lastest Dev I have no textures on the buttons and controlboards

**Comment by ukflyer** [comment]
All fine here - did you get the latest dev files posted a few hours ago that fixes the textures? Cheers

![altitude](https://user-images.githubusercontent.com/70434502/91749101-e4998e80-ebb8-11ea-966e-861032860a27.PNG)

**Comment by Kubakuurne** [comment]
I just registered didn't get it yet but I'll this evening for a new dev, all the rest is SUPER big thanks !!!

**Comment by ukflyer** [comment]
cool..  enjoy :)

**Comment by Curtis-VL** [comment]
@Kubakuurne If your issue is solved, please close the issue! :)

**Comment by griffon55** [comment]
I just try a fly tonight I put higher altitude and push managed altitude or selected and plane don't climb

**Comment by Curtis-VL** [comment]
@griffon55 Oh yeah, that's out of our hands. That's Asobo's problem I believe, the AP code is mostly shared between aircraft.
Sometimes it'll enter OP DES or OP CLB instantly, other times it'll take forever. :(

**Comment by michaeldiguiseppi** [comment]
@Kubakuurne is this issue resolved? If so i can close the issue for you.

@griffon55 yeah the autopilot is being worked on as much as we can, but there are some parts of it that are definitely out of our hand currently.

**Comment by Kubakuurne** [comment]
Looking good now , although i had to crank up all flood light settings to see the screens .
once it was lit al works fine :-)
