### ISSUE TITLE
Captured LOC in APPR but FMA still showing "HDG" and "LOC" gone

### ISSUE THREAD

**Issue by ZiCongQ** [wpine215/msfs-a320neo#299]
Before localizer captured:
![image](https://user-images.githubusercontent.com/70565899/91812451-b624bd80-ec63-11ea-9e29-765f021220a8.png)

After localizer captured:
![image](https://user-images.githubusercontent.com/70565899/91812512-ce94d800-ec63-11ea-93d8-d7ab89b9011a.png)

**Comment by ukflyer** [comment]
Hi,
Raised in https://github.com/wpine215/msfs-a320neo/issues/258

**Comment by ZiCongQ** [comment]
sry didnt find it before, refer to #258
