### ISSUE TITLE
FS2Crew

### ISSUE THREAD

**Issue by Tankieboy** [wpine215/msfs-a320neo#310]
Hi, loving your work!

Interested in getting FS2Crew and wondered if you knew of any issues?

**Comment by Benjozork** [comment]
Hello !

GitHub issues are strictly for bug reports. Please use the Discord server to ask any questions.

You can see on FS2Crew's YouTube channel that they expect their software to be compatible.

![image](https://user-images.githubusercontent.com/4503241/91872796-448a4680-ec46-11ea-88f4-b3f8284f89e2.png)

**Comment by Curtis-VL** [comment]
Please bring this up in Discord as the above comment says. :)

**Comment by Tankieboy** [comment]
Sorry, thank you
