### ISSUE TITLE
Expedite button not affected by brightness switch

### ISSUE THREAD

**Issue by ocram9** [wpine215/msfs-a320neo#311]
The expedite button isn't affected by the brightness switch. This also means that the button is the only one lit up when starting cold and dark.

![Screenshot_6](https://user-images.githubusercontent.com/49008532/91885068-6f48bf00-ec87-11ea-8447-4ad2eff27d46.png)

![Screenshot_7](https://user-images.githubusercontent.com/49008532/91885077-71128280-ec87-11ea-8541-e15fb68a90fd.png)

**Comment by PCGamesF1Tech** [comment]
No time for turnaround, time is money, little hint, expedite! 😜

**Comment by NathanInnes** [comment]
Looking into fixing it now.

**Comment by wpine215** [comment]
Fixed with #317
