### ISSUE TITLE
APU ECAM Page not showing N or EGT on landing

### ISSUE THREAD

**Issue by CoffeePanda0** [wpine215/msfs-a320neo#314]
![image](https://user-images.githubusercontent.com/34898787/91894702-044eb680-ec8e-11ea-85ec-ee3a42b88d21.png)
I can start the APU after landing, but the EGT and N% don't work

**Comment by AdenFlorian** [comment]
i think this was fixed by #298, please retest.

**Comment by Coralec** [comment]
I remember this being a problem in very early builds but have not seen the issue in my test flights for some time. I believe that #298 did indeed fix this problem. I attempted to replicate the problem but the APU ecam page displayed the startup properly. Unless more information can be supplied to help replicate this issue then I believe we can mark this as fixed.
