### ISSUE TITLE
Fma issue

### ISSUE THREAD

**Issue by griffon55** [wpine215/msfs-a320neo#321]
I just try with last dev # 289 to fix fma issue but I tried ils approach and when loc is captured loc message on FMA disappear same thing for G/S .as well if disengage autopilot  app disengage  and loc engage itself.

**Comment by wpine215** [comment]
Can you try to re-create the issue and post a short video? Would be super helpful

**Comment by Curtis-VL** [comment]
Was the flight director enabled? That could explain why the FMA modes weren't visible!
As for the issue with things disabling on AP disengagement, this may need to be brought out into its own issue on here. 👍

**Comment by griffon55** [comment]
Yes FD enabled.i'll a short video.

**Comment by griffon55** [comment]
Look on this video

**Comment by griffon55** [comment]
Look on this video

**Comment by griffon55** [comment]
https://s.amsu.ng/Xfjhaqts6EXN
