### ISSUE TITLE
Displays don't turn off with brightness set to "off"

### ISSUE THREAD

**Issue by topiek-fs** [wpine215/msfs-a320neo#334]
![afbeelding](https://user-images.githubusercontent.com/70661970/92027383-c1aade00-ed62-11ea-965e-43ab3eac594e.png)
![afbeelding](https://user-images.githubusercontent.com/70661970/92027432-d38c8100-ed62-11ea-901a-b9ee627527a6.png)

**Comment by nistei** [comment]
Duplicates #165

**Comment by Benjozork** [comment]
dup. #332, #165

**Comment by topiek-fs** [comment]
Fixed in #335

**Comment by topiek-fs** [comment]
Fixed and merged in #335
