### ISSUE TITLE
MCP Panel Font offset

### ISSUE THREAD

**Issue by miniarmagb** [wpine215/msfs-a320neo#34]
![Microsoft Flight Simulator 24_08_2020 19_36_02](https://user-images.githubusercontent.com/70097051/91082777-12268b00-e641-11ea-9725-b563b6d98783.png)
As you can see by the image, the V/S Speed is out of the MCP panel.

**Comment by LorDawid** [comment]
The right side of the MCP is just offset
=

**Comment by davidnorfolk96** [comment]
I have this too

**Comment by noga-aviator** [comment]
this is a duplicate of isssue #24 , i'm gonna close that
