### ISSUE TITLE
[BUG] PFD is in alignment when starting on the runway

### ISSUE THREAD

**Issue by ukflyer** [wpine215/msfs-a320neo#349]
**Describe the bug**
PFD is in alignment when starting on the runway.
Using latest dev files

**Expected behavior**
To be in alignment same as ND

**Screenshots or Videos**
![nddisplay](https://user-images.githubusercontent.com/70434502/92089289-da98ab00-edc5-11ea-9cc8-775617ec53d7.PNG)

**Comment by NathanInnes** [comment]
Working on it now.

**Comment by UncleClapton** [comment]
I get this as well. C&D start is fine.

**Comment by AdenFlorian** [comment]
@NathanInnes fixed this in #350 , I tested and it looks good, so closing this issue.
