### ISSUE TITLE
[BUG] Maybe its me. Made a new download of Dev-0.1.1 Apu Wont start

### ISSUE THREAD

**Issue by luiskjr** [wpine215/msfs-a320neo#352]
Hi, 
I made a fresh download of the Dev-0.1.1 76,222KB (i dont like the stable version cause nothing works), 
deleted previous A32NX dir from Community, installed the fresh new
and all of a sudden the APU wont start anymore. Any clues?
This was after the update
I can start the engines with external power but the batteries although seemed on none of the PFD work
all seems to be messed up

**Comment by Benjozork** [comment]
Please provide a detailed list of the steps you are taking to start the APU, we can't guess what you are doing :slightly_smiling_face:

**Comment by luiskjr** [comment]
Follow the Checklist, tick by tick
I think my main A320neo must be corrupt since this is totally absurd to happen

**Comment by luiskjr** [comment]
Do you know how to re-download just the A320 or must I do a full reinstall?

**Comment by wpine215** [comment]
Please use the discord for installation troubleshooting, not Github issues.
