### ISSUE TITLE
[BUG] Stuck on APU page

### ISSUE THREAD

**Issue by AdenFlorian** [wpine215/msfs-a320neo#357]
**Describe the bug**
You get stuck on a blank APU page on the lower ECAM when spawning on final and then starting the APU.

**To Reproduce**
1. Spawn on final for KDEN 16R
1. Note that APU page is available to switch to and from and has info on it
1. Press APU MASTER
1. Note that upper and lower ECAM screens are now blank, and that if you try to switch the lower ECAM page, it instantly snaps back to APU, which stays blank

**Expected behavior**
APU page should never be blank with power on and brightness up, and you shouldn't be prevented from switching off the APU page

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/3533988/92145404-cf517980-eddd-11ea-9293-eeead663ad5d.png)

**Additional context**
on dev branch, commit 0c4fbd9973911b4d666fa2c6f77f6402797b7da2

**Comment by AdenFlorian** [comment]
looking into this

**Comment by AdenFlorian** [comment]
Appears to have started occurring with this commit: https://github.com/wpine215/msfs-a320neo/commit/ee4cfc7737c276eaa4ddbf0e690adea7d7041cb3

Looking more into it...

@ThePilot916

**Comment by AdenFlorian** [comment]
I have a fix, implementing...

**Comment by Coralec** [comment]
Tested and working properly.

**Comment by AdenFlorian** [comment]
apparently this was a duplicate of #268 my bad
