### ISSUE TITLE
No chime coming from No smoking & Seatbelts. Also, they don't display on ECAM

### ISSUE THREAD

**Issue by davidnorfolk96** [wpine215/msfs-a320neo#36]
No chime coming from No smoking & Seatbelts. Also, they don't display on ECAM. I've tested it a few times over but no luck

**Comment by LorDawid** [comment]
I have the same problem with sounds

**Comment by noga-aviator** [comment]
are chime sound even implemented yet ?

**Comment by opdelta** [comment]
I'm currently working on adding sounds to the seatbelt and no smoking signs.

**Comment by davidnorfolk96** [comment]
Rgr, thanks guys! great work so far

**Comment by arvinjarvin** [comment]
Hello!

This is being presently progressed by our avid development team.

Thanks for raising the issue and should you have any more requests or issues please let us know

All the best
Arvin

**Comment by luiskjr** [comment]
Its working now for me, the two dings seat belts and no smoking
