### ISSUE TITLE
[BUG] Starting a flight mid-flight sets the engine ignition switch to crank mode.

### ISSUE THREAD

**Issue by UncleClapton** [wpine215/msfs-a320neo#370]
**Branch**
dev

**Describe the bug**
When starting mid-flight, the ignition switch starts in crank mode.

**To Reproduce**
1. Start a flight in mid-flight, or start on the ground and use "travel to" menu to move to a in-flight stage.
2. See that the ignition switch is put in crank.

**Expected behavior**
ignition switch should be in "norm" mode.

**Screenshots or Videos**
![](https://clapton.dev/u/2009/86ac08da.png)

**Comment by benjwri** [comment]
Believe I've fixed this, will pull request in a minute
