### ISSUE TITLE
[BUG] PFD Freezes when engaging LOC or APPR

### ISSUE THREAD

**Issue by dcherrie** [wpine215/msfs-a320neo#371]
**Branch**
DEV 0.1.1

**Describe the bug**
When engaging LOC or APP whilst the autopilot is engaged, the PDF freezes.

**To Reproduce**
Setup for an ILS landing and engage LOC then APP.

**Expected behavior**
The PDF not feeze.

**Screenshots or Videos**
https://www.youtube.com/watch?v=ptp-xhwtEl0
https://www.youtube.com/watch?v=FCc_i19c0Zw

**Additional context**
Tried on a second flight and could not reproduce.
Tried on a third flight and happened as before shown in second video.

**Comment by UncleClapton** [comment]
I can take a look into this one

**Comment by UncleClapton** [comment]
leaving for Curtis 
![](https://clapton.dev/u/2009/93db4da8.png)

**Comment by Curtis-VL** [comment]
Thanks, correcting!

I tried it out before merging, but it looks like I forgot to refresh the cache, so it loaded old code. My bad!

**Comment by Curtis-VL** [comment]
Corrected in #374, sorry about this! Lesson learnt. 👍

**Comment by Curtis-VL** [comment]
#374 has been merged, issue is resolved, thanks for the report!
