### ISSUE TITLE
Are you aware dev-0.1.1 is not working after the update? please send link to discord channel [BUG]

### ISSUE THREAD

**Issue by luiskjr** [wpine215/msfs-a320neo#373]
**Branch**
Which branch of the code is the issue present in?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by Curtis-VL** [comment]
What exactly is the issue with the dev branch? Just not loading?

**Comment by 0nnyx** [comment]
Working fine for me, except the speed indicator, heading, vs remaining blank when doing a dark & cold startup (or maybe I didn't find the brightness knob for that ?)

**Comment by ArthurHetem** [comment]
I have no troubles, working for me

**Comment by Gurkonier** [comment]
> 
> 
> Working fine for me, except the speed, heading, altitude and VS selector displays remaining blank when doing a dark & cold startup (or maybe I didn't find the brightness knob for that ?)

Same issue for me

**Comment by Benjozork** [comment]
@Gurkonier @0nnyx please send screenshots of the issue so we can figure out if we need to open an issue for this.

**Comment by UncleClapton** [comment]
@0nnyx & @ArthurHetem, try the knobs associated with the panels in this image: https://media.discordapp.net/attachments/738864300818432023/750409540918444072/A320_screens.png

**Comment by ArthurHetem** [comment]
> @0nnyx & @ArthurHetem, try the knobs associated with the panels in this image: https://media.discordapp.net/attachments/738864300818432023/750409540918444072/A320_screens.png

I have no troubles, i think that it's for @Gurkonier

**Comment by wpine215** [comment]
Issue did not follow template. Closing.
