### ISSUE TITLE
Game Pass Folder can be different

### ISSUE THREAD

**Issue by feiercrack** [wpine215/msfs-a320neo#39]
As mentioned here [https://github.com/wpine215/msfs-a320neo#installation](url)

my game pass edt. community folder is NOT there.

if its an custom installation folder, we can find the folder here:

YorDrive:\YourInstallionFolder\MSFlightSim2020\Community

**Comment by opdelta** [comment]
Custom installation folders have been added to the installation instructions in the README. Depending on your custom content installation folder, instructions has been added to find your community folder if you forgot your custom path.

The pull is awaiting review. This issue should be fixed.

**Comment by wpine215** [comment]
Fixed in pull request #41
