### ISSUE TITLE
Disconnect from Catering and Baggage is swapped

### ISSUE THREAD

**Issue by feiercrack** [wpine215/msfs-a320neo#42]
As described, when i disconnect the baggae, the catering will disconnect.
when disconnnect the catering, baggage will disconnect
this happens, when both are connected at same time.

**Comment by noga-aviator** [comment]
ok, but this ground services are not a320 related

**Comment by noga-aviator** [comment]
ima close that, that really doesn't have anything to do with the a320

**Comment by feiercrack** [comment]
hey, of course it has to do with your airbus addon!
i just removed your folder, and tried  again. And everything works fine as it should.
please take your time to test this by yourself!

**Comment by michaeldiguiseppi** [comment]
I tested this. It works perfectly fine for me while using the mod. None of the code touches ATC commands. You should direct this bug to Asobo/Microsoft if you can reliably reproduce it, but I assure you, if you're using the mod correctly, it does not cause this issue.

**Comment by opdelta** [comment]
Same thing for me. I tried reproducing the issue and it worked fine. 
I am obviously not doubting you, but perhaps if you share a video or steps to reproduce it can help me pin the issue to either the mod or Asobo?

**Comment by feiercrack** [comment]
hm, weard.. strange!

i just put your updated version inside, and now it works correctly at EDDF!
I have to re-check again LGKO or KORS Airport (ORBX) where i saw this issue.. Dunno atm..Anyway, thanks!
