### ISSUE TITLE
Displays should not turn on in cold-and-dark state if only on battery

### ISSUE THREAD

**Issue by wpine215** [wpine215/msfs-a320neo#45]
Displays should require generator power from GPU, APU, or engine(s) to display properly. This should also resolve the "issue" with displays remaining on "power on self test" when only on battery, since they shouldn't be on at all

**Comment by ninjomcs** [comment]
Will try to implement this.

**Comment by ninjomcs** [comment]
Implemented, made a pull request.

**Comment by wpine215** [comment]
Issue has been fixed.
