### ISSUE TITLE
APU Gen info on APU ECAM page displays connected arrow even when aircraft is still connected to external power

### ISSUE THREAD

**Issue by wpine215** [wpine215/msfs-a320neo#47]

**Comment by noga-aviator** [comment]
could you be more precise ? Screenshots ?

**Comment by wpine215** [comment]
If the A320 is still connected to external power (EXT PWR is illuminated with a blue "ON"), then the arrow pointing up, right above the APU GEN info box on the upper left hand corner of the APU ECAM page, should not display, since it is visible only when the APU is supplying power, which is not the case while EXT PWR is illuminated blue ON.

**Comment by wpine215** [comment]
Issue is fixed.
