### ISSUE TITLE
APU start button should work even if flap is not open yet

### ISSUE THREAD

**Issue by wpine215** [wpine215/msfs-a320neo#53]
In the airplane, when you hit the APU Master switch, you don't have to wait for the FLAP OPEN to hit the start button. If you hit one after the other, the start waits for the FLAP OPEN to start the cycle.

**Comment by noga-aviator** [comment]
ok, will try to implement

**Comment by Blumski1** [comment]
The starter PB light still illuminates even when the flap is in transition and the starter hasn't engaged yet.

**Comment by becas22** [comment]
However, you should wait 3sec between master on and start press

**Comment by JackZ974** [comment]
I'm on it. reduced the time to 3 seconds.

**Comment by becas22** [comment]
Nooo, the flap shouldn't open in 3 seconds! It's the time you wait to press START P/B

**Comment by Blumski1** [comment]
And that is why I didn't mention the 3 seconds, it has nothing to do with the switch logic. The starter obeys the FLAP OPEN.

Waiting 3 seconds ensures that the "LOW OIL LEVEL" message is not displayed prior to starting the APU. If the message is displayed, refer to the QRH ECAM Advisory section and notify Maintenance.

**Comment by JackZ974** [comment]
Yes. I know. But for now the logic that has been implemented in the js code is that the START button is linked to the FLAP OPEN. The delay for Flap open was set initially to 20 sec (like in the old CEO), so the START button was inop until then. @Dalmont confirmed me that in the NEO the FLAP OPEN Appears after 3 to 5 sec only. SO i reduced the FLAP apparition time from 20 to 3. 

Temporary fix.

**Comment by JackZ974** [comment]
> 
> 
> Nooo, the flap shouldn't open in 3 seconds! It's the time you wait to press START P/B

This is Company procedure, but there is nothing in the FCOM about the fact that you should wait 3 seconds before switching the MASTER ON

**Comment by JackZ974** [comment]
> 
> 
> And that is why I didn't mention the 3 seconds, it has nothing to do with the switch logic. The starter obeys the FLAP OPEN.
> 
> Waiting 3 seconds ensures that the "LOW OIL LEVEL" message is not displayed prior to starting the APU. If the message is displayed, refer to the QRH ECAM Advisory section and notify Maintenance.

In fact, You are allowed to press the start button right after the master. The APU simply won't start until the falp is fully open (around 10 to 20 sec on CEOs, 3 to 5 sec on NEO apparently)

**Comment by Blumski1** [comment]
@JackZ974, That's exactly what I said above. I don't know why we are talking about the 3 seconds, it has nothing to do with switch logic.

**Comment by JackZ974** [comment]
because @Becas talked about it! LOL

**Comment by becas22** [comment]
> > Nooo, the flap shouldn't open in 3 seconds! It's the time you wait to press START P/B
> 
> This is Company procedure, but there is nothing in the FCOM about the fact that you should wait 3 seconds before switching the START after the MASTER ON

Take a look here: 
![image](https://user-images.githubusercontent.com/11005754/91592880-1a3f3d00-e957-11ea-8fdb-3e046a613f11.png)

Sorry to bring the 3 second stuff into the equation.

**Comment by Kevin-Konradi** [comment]
Yes, but the logic still allows you to press the APU START button right after the master switch, that's why there's the note. Else it wouldn't be there

**Comment by becas22** [comment]
> Yes, but the logic still allows you to press the APU START button right after the master switch, that's why there's the note. Else it wouldn't be there

I know, that's why in my original comment I said you should wait. I was not hoping to create this confusion just because of a P/B lol

**Comment by Kevin-Konradi** [comment]
> 
> 
> > > Nooo, the flap shouldn't open in 3 seconds! It's the time you wait to press START P/B
> > 
> > 
> > This is Company procedure, but there is nothing in the FCOM about the fact that you should wait 3 seconds before switching the START after the MASTER ON
> 
> Take a look here:
> ![image](https://user-images.githubusercontent.com/11005754/91592880-1a3f3d00-e957-11ea-8fdb-3e046a613f11.png)
> 
> Sorry to bring the 3 second stuff into the equation.

Sorry, i wanted to quote this :D

**Comment by JackZ974** [comment]
> 
> 
> > > > Nooo, the flap shouldn't open in 3 seconds! It's the time you wait to press START P/B
> > > 
> > > 
> > > This is Company procedure, but there is nothing in the FCOM about the fact that you should wait 3 seconds before switching the START after the MASTER ON
> > 
> > 
> > Take a look here:
> > ![image](https://user-images.githubusercontent.com/11005754/91592880-1a3f3d00-e957-11ea-8fdb-3e046a613f11.png)
> > Sorry to bring the 3 second stuff into the equation.
> 
> Sorry, i wanted to quote this :D

Before SELECTING, that doesn't mean that the START P/B is not illuminated right after MASTER is on. In my airline SOP they even increased the delay to 10 seconds in the SOPs!
Anyways... that's just a Sim...

**Comment by NathanInnes** [comment]
#223

**Comment by NathanInnes** [comment]
Fix APU time #223

**Comment by ThePilot916** [comment]
Fixed this issue here #230

**Comment by AdenFlorian** [comment]
From what I've read and people I've talked to, this is the expected scenario:

0s press APU MASTER and then ON in blue immediately lights up on the button
0.5s press APU START button, nothing happens
20s FLAP is now open, APU is now starting, and the APU START button has ON in blue

The APU will not begin starting up until the FLAP is fully open.

The APU START button will not light until the FLAP is open and the APU START button has been pressed at least once since the APU MASTER was switched on.

You don't have to wait for the FLAP to open before pressing APU START.
You can press it after APU MASTER is ON.

**Comment by AdenFlorian** [comment]
The current implementation on the dev branch is this, which I think is incorrect:

scenario A:
0s press APU MASTER and then ON in blue immediately lights up on the button
0.5s press APU START button, nothing happens
20s FLAP is now open, APU is NOT starting, and the APU START button is dark

scenario B:
0s press APU MASTER and then ON in blue immediately lights up on the button
3s press APU START button and then ON in blue immediately lights up on the button, and the APU starts starting up
20s FLAP is now open, APU is still starting

**Comment by AdenFlorian** [comment]
> 
> 
> From what I've read and people I've talked to, this is the expected scenario:
> 
> 0s press APU MASTER and then ON in blue immediately lights up on the button
> 0.5s press APU START button, nothing happens
> 20s FLAP is now open, APU is now starting, and the APU START button has ON in blue
> 
> The APU will not begin starting up until the FLAP is fully open.
> 
> The APU START button will not light until the FLAP is open and the APU START button has been pressed at least once since the APU MASTER was switched on.
> 
> You don't have to wait for the FLAP to open before pressing APU START.
> You can press it after APU MASTER is ON.

Working on implementing this now.

**Comment by JackZ974** [comment]
That's the way how it works effectively IRL. 
Even though the FCOM does recommends to wait at least 3 seconds before pressing the APU START P/B, the APU START P/B is available as soon as the GAPCU is energized by the APU MASTER P/B.
But the APU will not start before the flap is fully opened, for obvious reasons. Apparently the 20 seconds delay for FALPS openeing has been reduced on the NEO to around 8 seconds only.

**Comment by AdenFlorian** [comment]
@JackZ974 if you press the APU START immediately after pressing APU MASTER, when will the APU START ON light up? Immediately, after ~3 seconds, or when flap is fully open?

**Comment by JackZ974** [comment]
The APU START button will light immediately upon being pressed, that's a feedback that your command has been acknowledged, as for any push button.
This even though the real startup APU process will begin only when the APU FLAP is fully open.

**Comment by AdenFlorian** [comment]
This should be fixed after #355 gets merged.

After that gets merged it will follow this logic:

0s press APU MASTER and then ON in blue immediately lights up on the button
0.5s press APU START button and then ON in blue immediately lights up on the button
20s FLAP is now open, APU is now starting

The APU will not begin starting up until the FLAP is fully open.

The APU START button will be lit as long as it is pressed at any time after the APU MASTER button was turned on.

You don't have to wait for the FLAP to open before pressing APU START.
You can press it after APU MASTER is ON.

**Comment by AdenFlorian** [comment]
fixes are merged, issue is ready to test.

**Comment by wpine215** [comment]
Fixed.
