### ISSUE TITLE
APU EGT temperature settles on 10C after shutdown regardless of outside ambient air temp

### ISSUE THREAD

**Issue by wpine215** [wpine215/msfs-a320neo#54]
![image](https://user-images.githubusercontent.com/28059870/91113511-9de8e900-e63a-11ea-9be2-d42fe9e3c214.png)

**Comment by noga-aviator** [comment]
@tyler58546 you did the apu start system no ?

**Comment by 1Revenger1** [comment]
Mind assigning this to me? Taking a look at it right now.

**Comment by wpine215** [comment]
Fixed by #100
