### ISSUE TITLE
APU ECAM: Implement second or two delay between APU master on and display showing APU gen box, gauge needles, and gauge values

### ISSUE THREAD

**Issue by wpine215** [wpine215/msfs-a320neo#60]
Before APU master turned on and FADEC self test ends:
![image](https://user-images.githubusercontent.com/28059870/91122376-0a6de300-e64f-11ea-8f2c-9ed759c8e786.png)

After APU master turned on and FADEC self test completed, but before flap opens:
![image](https://user-images.githubusercontent.com/28059870/91122384-1194f100-e64f-11ea-97c0-64b75f8c0159.png)

**Comment by noga-aviator** [comment]
fixed in latest dev branch
