### ISSUE TITLE
Create project website using github pages

### ISSUE THREAD

**Issue by mszekiel** [wpine215/msfs-a320neo#75]
As in title. Create additional branch `gh-pages-source` which will build the page on `gh-pages` branch.
Tech stack: 
- React.JS
- Bootstrap

Please assign it to me :)

**Comment by foestauf** [comment]
I work with React and can help with the website. Also familiar with Gatsby to make it speedy zip zoom zoom.

**Comment by mszekiel** [comment]
@foestauf  I'm not familiar with Gatsby, can it help build the site faster? 
And when it comes to the design I think we should follow something simple and clear. 
Colors proposition: https://www.figma.com/file/OvRdwFGQxAMerMOqy4niBK/Untitled?node-id=2%3A15

**Comment by foestauf** [comment]
@mszekiel it's a SSG framework for React. Great for fast loading static sites with tons of great features built in like lazy loading/pre-fetching, plugins for almost anything. Only things that are a little different is routing, it uses reach-router currently. I use it on my GH-pages profile if you wanna take a peak at that. I can get it setup if you like. I'm not a designer so I will take you lead on the color scheme and wireframe.

**Comment by mszekiel** [comment]
@foestauf give me please your Discord handle, or message me Xanax#1282
