### ISSUE TITLE
LS Button turned on by itself during selftest with insane brightness

### ISSUE THREAD

**Issue by DoToAdventures** [wpine215/msfs-a320neo#77]
After turning on both batteries for some reason both FD and LS buttons turned on with the LS Button  having very very high brightness. Not sure how to reproduce it yet, will update once I find a way. 
https://i.imgur.com/u7qpY6q.jpeg

**Comment by arvinjarvin** [comment]
Hello!

Thanks for bringing this to our attention.

It will be fixed accordingly and you will be kept updated

**Comment by wpine215** [comment]
Has this been fixed? I haven't encountered it

**Comment by arvinjarvin** [comment]
Hello.

We have been unable to replicate this.

If you do encounter this again please let us know, and if possible try to find a way to replicate it.

I have looked over some segments of code and I do not believe that this should be affected by any of the work.

Once again if this is just a one off, we apologise for the inconvenience. If this happens again please let us know!

All the best
Arvin
