### ISSUE TITLE
Where is the actual source code

### ISSUE THREAD

**Issue by eisenfaust12** [wpine215/msfs-a320neo#79]
Hi,
I want to improve the (non-existing) FBW system of the A320Neo among other things. But all of the files here appear to be mostly configuration files and HTML/JS/CSS for rendering and driving the displays. Where is the actual core logic of all the systems and what language is it in? Is it Javascript as well ? Or is it a separate C/C++ or possibly .net DLL? Where can I find it? Also the JS files look like they were transpiled from TypeScript. If so are the original TypeScript files available also?

**Comment by michaeldiguiseppi** [comment]
The JS files live in the official folder of your sim installation. Any files that you put into the project here will overwrite the ones in the official folder of the same name. So things can get added as needed. As far as i'm aware they are not written using typescript, at least not that anyone in the project has found. All of the logic is in JS and XML, along with a little HTML and CSS for the gauges.
