### ISSUE TITLE
Wrong install location in readme

### ISSUE THREAD

**Issue by ocram9** [wpine215/msfs-a320neo#8]
The installation instructions in the readme point to Appdata/roaming but the actual (standard) file path is: AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community

**Comment by opdelta** [comment]
It was fixed in the last project merge! 
The readme should now contain the right installation paths for all installation locations depending on your edition and how to find your own community folder.

**Comment by wpine215** [comment]
Issue resolved, closing.
