### ISSUE TITLE
PFD screens start off when starting from a runway with engines running

### ISSUE THREAD

**Issue by michaeldiguiseppi** [wpine215/msfs-a320neo#84]
The PFD screens are starting blanked and off when loading into the sim on a runway with engines and APU running. They should only start dark when Cold/Dark or when Engines/APU are not on.

**Comment by wpine215** [comment]
Might need to modify APRON.flt and/or TAXI.flt to get this fixed, just a heads up to whoever works on it

**Comment by ninjomcs** [comment]
Fixed in latest PR

**Comment by arvinjarvin** [comment]
Thanks for raising this issue.

This has now been fixed in a PR as aforementioned

All the best
Arvin
