### ISSUE TITLE
PFD's are stuck on self test, and show self test when only on battery

### ISSUE THREAD

**Issue by wpine215** [wpine215/msfs-a320neo#89]
![image](https://user-images.githubusercontent.com/28059870/91238912-fa0f4400-e6f2-11ea-9254-f2b68824360e.png)

![image](https://user-images.githubusercontent.com/28059870/91238924-fed3f800-e6f2-11ea-81f6-eaaebaea2a34.png)

**Comment by tyler58546** [comment]
Unable to reproduce.

**Comment by noga-aviator** [comment]
just turn on battery, you will see that self test begins, but never ends

**Comment by noga-aviator** [comment]
also it shouldn't begin with battery

**Comment by wpine215** [comment]
Issue seems to have resolved itself for me, odd. If a third person can confirm it's not happening to them I'll go ahead and close this.

**Comment by noga-aviator** [comment]
i'll try then

**Comment by noga-aviator** [comment]
tomorow XD

**Comment by dcherrie** [comment]
@tyler58546 @wpine215 I can re-produce this as well and used a download from 5 days ago and now the latest DEV as well. From cold and dark, I switch on the battery and then switch on ground power. All screens have the SELF TEST message which never goes away.

![Desktop Screenshot 2020 08 31 - 14 38 26 57 1080](https://user-images.githubusercontent.com/22925698/91683420-f880c880-eb97-11ea-81d4-810ae67077c3.png)
