### ISSUE TITLE
APU unable to start at different parts of the flight

### ISSUE THREAD

**Issue by starvingjavi** [wpine215/msfs-a320neo#93]
APU master is able to start, but the flap won't open and when hovering the mouse on the button for APU start it says that it is unavailable.

**Comment by donstim** [comment]
I'm having problems starting the APU (master on) from a cold and dark start on the ground with battery and external power on the airplane. As above, hovering the mouse shows it is unavailable.

**Comment by ACSoft47** [comment]
I can confirm this problem. Had the same after landing and triying to start APU during taxi to the gate.

**Comment by AdenFlorian** [comment]
anyone know if this is still an issue in latest dev branch?

**Comment by starvingjavi** [comment]
I confirm it has been resolved during flight. I'm going to check after landing

**Comment by starvingjavi** [comment]
It has been resolved for landing aswell
